sudo: required
language: php
dist: trusty
php:
  - 7.1
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE snippets_testing;'
install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
before_script:
  - cp .env.testing .env
  - php artisan key:generate
script:
  - vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    secure: onHgZ7hxOQCDdHI/AfpnzSVR5SEUNI6RhAgogav89BdFos803n21LGxY94Esg0KqwQx7oEooAWqlIc3ZNuaYh+IPx5I3KnrhR64ttVCoPfd06Z6FEEK+sYUglXNogvKPKJWFwVjpvlvUOzD73g9GQy/7tY9JX4S2nSxCFXMsA4i+EAz0wfCps2MgpsKCRG71Kx4ueX0kKZ0fBP2vhPXeNVVH3nwudnnCLql9EUiRx2f46YZ4TO8E2nS72oGbtpNNqGy9zrjkF0sV8A421VuSAmvtIU+th8IEKAMCkhbOmfAB4J+LXNx20sPxw1u8nQkCYUveN+rs69Kvp/n9qrOMzlEUtqPbWpj0KgOn6FWq+vBW5Q+LtdO1h6WNokQci9aDtg/ifL0QqbK7of3HNECoDcOx0qtTmAD+i7hhNL0mJBJlNlBR5Mwnq15Zd/GLTOk6YbcUd+JZ8IcnEae4FhW9e+em1eSBg2uPQDu64rEG9pEUF1yq/ppTGV/AyMcFWDzAfZ6z4r2vozwCKt2oo+8jpxLWIMud/sEravpQMjDIQZJZJvHJ7YbqWvwMC6xyr9g7JTFWm3g9824JYm4p9FdrLMOwmt/v0dKb0FZSdjYIBctlBzR2TyVSGp++WVQEVY+eUUlZN8NH15Bua7x5VgmlWyEAOnchrofRNGeksoUSxkU=
  app: warm-garden-28757
  on:
    repo: travisobregon/snippets
  run:
    - composer install -o --no-interactions
    - php artisan migrate --no-interaction --force
    - yarn && npm run production
    - php artisan route:cache
    - php artisan config:cache
    - php artisan queue:restart
notifications:
  slack: itt-devops:3h9i2RuAo1VWBTj9oCi5DWEQ
