sudo: required
language: php
dist: trusty

php:
  - 7.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE snippets_testing;'

install:
  - travis_retry composer install --no-interaction

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.testing .env
  - php artisan serve &

script:
  - php artisan dusk

notifications:
  slack: itt-devops:3h9i2RuAo1VWBTj9oCi5DWEQ
